import { EngineeringAssistanceEngine } from "../src/assistance/EngineeringAssistanceEngine";
import type { AssistanceActionKind } from "../src/assistance/types";
import type { Recommendation, RecommendationKind, RepositoryRecommendationReport } from "../src/recommendations/types";

function recommendation(kind: RecommendationKind, overrides: Partial<Recommendation> = {}): Recommendation {
  return {
    kind,
    category: "advisory",
    priority: "medium",
    reason: `reason for ${kind}`,
    supportingEvidence: [],
    ...overrides,
  };
}

function report(recommendations: Recommendation[]): RepositoryRecommendationReport {
  return { repositoryId: "alpha", generatedAt: new Date(), recommendations };
}

function assert(condition: boolean, message: string): void {
  console.log(`${condition ? "PASS" : "FAIL"} - ${message}`);
}

function actionKinds(actions: { kind: AssistanceActionKind }[]): AssistanceActionKind[] {
  return actions.map((a) => a.kind);
}

function main(): void {
  const engine = new EngineeringAssistanceEngine();

  // Empty recommendations -> empty proposals, no fallback synthesized
  {
    const result = engine.propose(report([]));
    assert(result.proposals.length === 0, "no recommendations -> no proposals (no synthesized fallback)");
    assert(result.repositoryId === "alpha", "repositoryId carried through from the report");
  }

  // Order preserved exactly as received — never re-sorted by this engine
  {
    const kinds: RecommendationKind[] = ["ReviewChanges", "PullRequired", "RepositoryReadyToShip"];
    const result = engine.propose(report(kinds.map((k) => recommendation(k))));
    assert(
      JSON.stringify(result.proposals.map((p) => p.recommendationKind)) === JSON.stringify(kinds),
      "proposal order exactly matches the order recommendations were received in — never re-sorted",
    );
  }

  // category/priority/reason carried through unchanged, never regenerated
  {
    const rec = recommendation("PullRequired", { category: "blocking", priority: "high", reason: "3 commits behind" });
    const result = engine.propose(report([rec]));
    const proposal = result.proposals[0];
    assert(proposal.category === "blocking" && proposal.priority === "high", "category and priority are carried over unchanged from the recommendation");
    assert(proposal.reason === "3 commits behind", "reason text is carried over verbatim, never regenerated by this engine");
  }

  // Every proposal has exactly one primary action, never inferred from array order
  {
    const allKinds: RecommendationKind[] = ["RepositoryReadyToShip", "RepeatedFailures", "PullRequired", "ReviewPullRequest", "ContinueSession", "ReviewChanges"];
    const result = engine.propose(report(allKinds.map((k) => recommendation(k))));
    for (const proposal of result.proposals) {
      const primaryActions = proposal.actions.filter((a) => a.isPrimary);
      assert(primaryActions.length === 1, `${proposal.recommendationKind} has exactly one primary action`);
    }
  }

  // RepositoryReadyToShip -> ExecuteShipWorkflow (primary), InspectRepository, DismissSuggestion
  {
    const result = engine.propose(report([recommendation("RepositoryReadyToShip")]));
    const proposal = result.proposals[0];
    assert(
      JSON.stringify(actionKinds(proposal.actions).sort()) === JSON.stringify(["DismissSuggestion", "ExecuteShipWorkflow", "InspectRepository"].sort()),
      "RepositoryReadyToShip -> [ExecuteShipWorkflow, InspectRepository, DismissSuggestion]",
    );
    const primary = proposal.actions.find((a) => a.isPrimary)!;
    assert(primary.kind === "ExecuteShipWorkflow", "RepositoryReadyToShip's primary action is ExecuteShipWorkflow, an engineering-oriented name, not a UI label");
    const dismissal = proposal.actions.find((a) => a.isDismissal)!;
    assert(dismissal.kind === "DismissSuggestion", "the deferral choice is DismissSuggestion");
  }

  // RepeatedFailures -> InspectRepository (primary), ContinueCurrentSession (not a dismissal — an active override)
  {
    const result = engine.propose(report([recommendation("RepeatedFailures")]));
    const proposal = result.proposals[0];
    const primary = proposal.actions.find((a) => a.isPrimary)!;
    assert(primary.kind === "InspectRepository", "RepeatedFailures's primary action is InspectRepository (analyze before continuing)");
    const secondary = proposal.actions.find((a) => !a.isPrimary)!;
    assert(secondary.kind === "ContinueCurrentSession" && secondary.isDismissal === false, "'continue anyway' maps to ContinueCurrentSession, and is not treated as a dismissal — it's an active choice to proceed");
  }

  // PullRequired -> PullLatestChanges (primary), DismissSuggestion
  {
    const result = engine.propose(report([recommendation("PullRequired")]));
    const primary = result.proposals[0].actions.find((a) => a.isPrimary)!;
    assert(primary.kind === "PullLatestChanges", "PullRequired's primary action is PullLatestChanges");
  }

  // ReviewPullRequest -> InspectPullRequest (primary, never a "create/open new PR" action), DismissSuggestion
  {
    const result = engine.propose(report([recommendation("ReviewPullRequest")]));
    const proposal = result.proposals[0];
    const primary = proposal.actions.find((a) => a.isPrimary)!;
    assert(primary.kind === "InspectPullRequest", "ReviewPullRequest's primary action is InspectPullRequest — reviewing the existing PR, never creating a new one");
    assert(!actionKinds(proposal.actions).includes("ExecuteShipWorkflow" as AssistanceActionKind), "no ship/create-adjacent action is offered for a review-existing-PR recommendation");
  }

  // ContinueSession -> ContinueCurrentSession (primary), DismissSuggestion
  {
    const result = engine.propose(report([recommendation("ContinueSession")]));
    const primary = result.proposals[0].actions.find((a) => a.isPrimary)!;
    assert(primary.kind === "ContinueCurrentSession", "ContinueSession's primary action is ContinueCurrentSession");
  }

  // ReviewChanges -> InspectRepository (primary), DismissSuggestion
  {
    const result = engine.propose(report([recommendation("ReviewChanges")]));
    const primary = result.proposals[0].actions.find((a) => a.isPrimary)!;
    assert(primary.kind === "InspectRepository", "ReviewChanges's primary action is InspectRepository");
  }

  // Determinism: identical input -> identical output
  {
    const input = report([recommendation("PullRequired"), recommendation("RepositoryReadyToShip")]);
    const first = engine.propose(input);
    const second = engine.propose(input);
    assert(
      JSON.stringify(first.proposals.map((p) => ({ kind: p.recommendationKind, actions: p.actions }))) ===
        JSON.stringify(second.proposals.map((p) => ({ kind: p.recommendationKind, actions: p.actions }))),
      "identical input produces identical proposals and actions",
    );
  }
}

main();
